[project]
name = 'Decentralized-Spiritual-Development-Quantum-Enlightenment-Pathways'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experience-integration]
path = 'contracts/experience-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.pathway-design]
path = 'contracts/pathway-design.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
